### ISSUE TITLE
滑动有时背景图片会加载不出来，或者白色

### ISSUE THREAD

**Issue by Liang-5** [tokiii/RevealBanner#2]
**在viewpage滑动监听里这个判断走的else**
if (mViewPagerIndex == position) {
                if (bannerBgContainer.getBannerBgViews().size() > position % bannerBgContainer.getBannerBgViews().size() + 1) {
                    bannerBgContainer.getBannerBgViews().get(position % bannerBgContainer.getBannerBgViews().size() + 1).bringToFront();
                    bannerBgContainer.getBannerBgViews().get(position % bannerBgContainer.getBannerBgViews().size() + 1)
                            .hideClipAnimation((positionOffset - reduceValue) * upValue > 1 ? 1 : (positionOffset - reduceValue) * upValue);
                } else if (bannerBgContainer.getBannerBgViews().size() == position % bannerBgContainer.getBannerBgViews().size() + 1) {
                    bannerBgContainer.getBannerBgViews().get(0).bringToFront();
                    bannerBgContainer.getBannerBgViews().get(0)
                            .hideClipAnimation((positionOffset - reduceValue) * upValue > 1 ? 1 : (positionOffset - reduceValue) * upValue);
                }
            } **else {//空白时，走的是这个判断
                if (position / bannerBgContainer.getBannerBgViews().size() >= 0) {
                    bannerBgContainer.getBannerBgViews().get(position % bannerBgContainer.getBannerBgViews().size()).bringToFront();
                    bannerBgContainer.getBannerBgViews().get(position % bannerBgContainer.getBannerBgViews().size())
                            .showClipAnimation(0, bannerBgContainer.getHeight() / 2,
                                    (1 - (positionOffset + reduceValue)) * upValue > 1 ? 1 : (1 - (positionOffset + reduceValue)) * upValue);
                }**
}

**Comment by tokiii** [comment]
我这没复现出来这个问题，是Demo出的问题么？

**Comment by lyyzfb** [comment]
> 
> 
> 我这没复现出来这个问题，是Demo出的问题么？

**Comment by Liang-5** [comment]
在滑动完之后，在继续滑下一个banner，放大动画没有执行,这样滑动几个之后，背景图重新绘制好像有点问题

**Comment by tokiii** [comment]
好，我抽空看看这个问题.

**Comment by yangruixiang** [comment]
你好，请问这个问题解决了吗？我这边项目准备用这个了，看见了麻烦回一下，谢谢

**Comment by tokiii** [comment]
暂时没发现问题，如果能复现提供demo或必现操作步骤，谢谢.

**Comment by SherlockGougou** [comment]
只有一张banner和背景时有这个问题，可以复现。
