### ISSUE TITLE
时间较长半小时到一小时后，会出现卡顿现象

### ISSUE THREAD

**Issue by Muran-Hu** [tokiii/RevealBanner#5]
停留在轮播图页面时间较长，半小时到一小时过后，轮播图会卡顿，请看一下，谢谢！

**Comment by whosmyqueen** [comment]
我也出现这个问题，貌似是缩放动画的问题

**Comment by whosmyqueen** [comment]
@tokiii 大佬，这个问题解决了吗

**Comment by tokiii** [comment]
> @tokiii 大佬，这个问题解决了吗

最近抽时间正在解决.

**Comment by Muran-Hu** [comment]
非常感谢! 👍

**Comment by testwanxue** [comment]
这个问题好像是动画那一块   请大佬尽快修复 谢谢！

**Comment by testwanxue** [comment]
时间长了 内存溢出问题  帮忙解决一下

**Comment by tokiii** [comment]
这个我问题我修改了，你们用demo再测试一下，如果可以我晚点儿在jcenter发布一版.

**Comment by tokiii** [comment]
已经更新至1.0.2.
